### ISSUE TITLE
[Bug] Sub Sub Tasks are not calcuated into sub task

### ISSUE THREAD

**Issue by mreishman** [joshpalan/Tasky#16]
Bug: When adding a sub task to another sub task, it doesn't add the time for the sub sub tasks to the sub task. 

Image: 
![image](https://user-images.githubusercontent.com/3468153/43323615-bde2748e-9177-11e8-850c-04210fbf4fff.png)

**Comment by barricade823** [comment]
👍🏼👍🏼 picking this up right now.
